//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmerseWebSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int uID { get; set; }
        public string uName { get; set; }
        public string uUSerName { get; set; }
        public string uPassword { get; set; }
        public string uEmail { get; set; }
    }
}
